name: FindPlayer
main: findPlayer.FindPlayer
version: 0.5
authors:
    - PenalBuffalo
api-version: 1.13
softdepend: [WorldGuard]
description: Finds locations of players
commands:
   findp:
         description: This command returns a player's coordinates. If configured with logging it will also store player's coordinates when they are offline.
         usage: /findp [player]
         permission: FindPlayer.findp
         permission-message: You don't have access to FindPlayer.findp!